// Grouped from the Eendrag/SACS alumni occupation data.
// "Other" is handled separately in the UI (shows a text input).
export const INDUSTRIES = [
  'Accounting & Finance',
  'Agriculture & Wine',
  'Architecture & Design',
  'Construction & Property',
  'Consulting & Professional Services',
  'Education & Academia',
  'Energy & Environment',
  'Engineering',
  'Entrepreneurship',
  'Government & Public Sector',
  'Hospitality & Tourism',
  'Legal',
  'Manufacturing & Industrial',
  'Marketing, Media & Creative',
  'Medical & Healthcare',
  'Military & Defence',
  'Mining & Resources',
  'Retail & Wholesale',
  'Sport',
  'Technology & IT',
  'Transport & Logistics',
  'Retired',
  'Student',
]

// Curated list of major South African cities/towns, so the directory filter
// stays clean instead of accumulating "Cape Town" / "CPT" / "Kaapstad" as
// separate values. Profiles outside SA still use free text — see Profile.jsx.
export const SA_CITIES = [
  'Cape Town', 'Stellenbosch', 'Paarl', 'Somerset West', 'Bellville',
  'Durbanville', 'Kuils River', 'Brackenfell', 'Parow', 'Goodwood',
  'Milnerton', 'Table View', 'Constantia', 'Claremont', 'Rondebosch',
  'Sea Point', 'Camps Bay', 'Hermanus', 'Worcester', 'Wellington',
  'Franschhoek', 'George', 'Knysna', 'Mossel Bay', 'Oudtshoorn',
  'Saldanha', 'Vredenburg', 'Malmesbury',
  'Johannesburg', 'Sandton', 'Randburg', 'Roodepoort', 'Centurion',
  'Pretoria', 'Midrand', 'Benoni', 'Boksburg', 'Krugersdorp',
  'Durban', 'Umhlanga', 'Pietermaritzburg', 'Ballito',
  'Gqeberha (Port Elizabeth)', 'East London',
  'Bloemfontein', 'Kimberley', 'Polokwane', 'Nelspruit (Mbombela)',
  'Rustenburg', 'Potchefstroom', 'Mahikeng',
]

export const SA_PROVINCES = [
  'Western Cape',
  'Gauteng',
  'KwaZulu-Natal',
  'Eastern Cape',
  'Free State',
  'Limpopo',
  'Mpumalanga',
  'North West',
  'Northern Cape',
]

export const COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda',
  'Argentina','Armenia','Australia','Austria','Azerbaijan',
  'Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize',
  'Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil',
  'Brunei','Bulgaria','Burkina Faso','Burundi',
  'Cambodia','Cameroon','Canada','Cape Verde','Central African Republic',
  'Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica',
  'Croatia','Cuba','Cyprus','Czech Republic',
  'Democratic Republic of the Congo','Denmark','Djibouti','Dominica',
  'Dominican Republic',
  'East Timor','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea',
  'Estonia','Eswatini','Ethiopia',
  'Fiji','Finland','France',
  'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala',
  'Guinea','Guinea-Bissau','Guyana',
  'Haiti','Honduras','Hungary',
  'Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy',
  'Ivory Coast',
  'Jamaica','Japan','Jordan',
  'Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan',
  'Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein',
  'Lithuania','Luxembourg',
  'Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Mauritania',
  'Mauritius','Mexico','Moldova','Monaco','Mongolia','Montenegro','Morocco',
  'Mozambique','Myanmar',
  'Namibia','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria',
  'North Korea','North Macedonia','Norway',
  'Oman',
  'Pakistan','Panama','Papua New Guinea','Paraguay','Peru','Philippines',
  'Poland','Portugal',
  'Qatar',
  'Romania','Russia','Rwanda',
  'Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines',
  'Samoa','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone',
  'Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
  'South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan',
  'Suriname','Sweden','Switzerland','Syria',
  'Taiwan','Tajikistan','Tanzania','Thailand','Togo','Tonga',
  'Trinidad and Tobago','Tunisia','Turkey','Turkmenistan',
  'Uganda','Ukraine','United Arab Emirates','United Kingdom',
  'United States','Uruguay','Uzbekistan',
  'Vanuatu','Vatican City','Venezuela','Vietnam',
  'Yemen',
  'Zambia','Zimbabwe',
]
