// Grouped from the Eendrag/SACS alumni occupation data.
// "Other" is handled separately in the UI (shows a text input).
export const INDUSTRIES = [
  'Accounting & Finance',
  'Agriculture & Wine',
  'Architecture & Design',
  'Civil Engineering',
  'Software Engineering & Development',
  'Mechanical/Manufacturing Engineering',
  'Other Engineering (electrical, chemical, marine, etc.)',
  'Banking & Financial Services',
  'Insurance & Actuarial Science',
  'Investment & Asset Management',
  'Construction & Project Management',
  'Property & Real Estate',
  'Legal',
  'Consulting',
  'Management & Operations',
  'Human Resources & Recruitment',
  'Marketing & Advertising',
  'Media & Creative (publishing, film, design)',
  'Public Relations & Communications',
  'Education & Academia',
  'Research & Development',
  'Healthcare & Medical',
  'Pharmaceuticals & Biotech',
  'Mental Health & Psychology',
  'Energy & Environment',
  'Mining & Resources',
  'Manufacturing & Industrial',
  'Hospitality & Tourism',
  'Food & Beverage',
  'Retail & Wholesale',
  'E-commerce',
  'Transport & Logistics',
  'Telecommunications',
  'Utilities & Water',
  'Government & Public Sector',
  'Non-profit & NGO',
  'Sport & Recreation',
  'Arts & Entertainment',
  'Military & Defence',
  'Retired',
  'Student',
]

// Curated list of major South African cities/towns, so the directory filter
// stays clean instead of accumulating "Cape Town" / "CPT" / "Kaapstad" as
// separate values. Profiles outside SA still use free text — see Profile.jsx.
export const SA_CITIES = [
  'Cape Town', 'Stellenbosch', 'Paarl', 'Somerset West', 'Bellville',
  'Durbanville', 'Kuils River', 'Brackenfell', 'Parow', 'Goodwood',
  'Milnerton', 'Table View', 'Constantia', 'Claremont', 'Rondebosch',
  'Sea Point', 'Camps Bay', 'Hermanus', 'Worcester', 'Wellington',
  'Franschhoek', 'George', 'Knysna', 'Mossel Bay', 'Oudtshoorn',
  'Saldanha', 'Vredenburg', 'Malmesbury',
  'Johannesburg', 'Sandton', 'Randburg', 'Roodepoort', 'Centurion',
  'Pretoria', 'Midrand', 'Benoni', 'Boksburg', 'Krugersdorp',
  'Durban', 'Umhlanga', 'Pietermaritzburg', 'Ballito',
  'Gqeberha (Port Elizabeth)', 'East London',
  'Bloemfontein', 'Kimberley', 'Polokwane', 'Nelspruit (Mbombela)',
  'Rustenburg', 'Potchefstroom', 'Mahikeng',
]

export const COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda',
  'Argentina','Armenia','Australia','Austria','Azerbaijan',
  'Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize',
  'Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil',
  'Brunei','Bulgaria','Burkina Faso','Burundi',
  'Cambodia','Cameroon','Canada','Cape Verde','Central African Republic',
  'Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica',
  'Croatia','Cuba','Cyprus','Czech Republic',
  'Democratic Republic of the Congo','Denmark','Djibouti','Dominica',
  'Dominican Republic',
  'East Timor','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea',
  'Estonia','Eswatini','Ethiopia',
  'Fiji','Finland','France',
  'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala',
  'Guinea','Guinea-Bissau','Guyana',
  'Haiti','Honduras','Hungary',
  'Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy',
  'Ivory Coast',
  'Jamaica','Japan','Jordan',
  'Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan',
  'Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein',
  'Lithuania','Luxembourg',
  'Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Mauritania',
  'Mauritius','Mexico','Moldova','Monaco','Mongolia','Montenegro','Morocco',
  'Mozambique','Myanmar',
  'Namibia','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria',
  'North Korea','North Macedonia','Norway',
  'Oman',
  'Pakistan','Panama','Papua New Guinea','Paraguay','Peru','Philippines',
  'Poland','Portugal',
  'Qatar',
  'Romania','Russia','Rwanda',
  'Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines',
  'Samoa','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone',
  'Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
  'South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan',
  'Suriname','Sweden','Switzerland','Syria',
  'Taiwan','Tajikistan','Tanzania','Thailand','Togo','Tonga',
  'Trinidad and Tobago','Tunisia','Turkey','Turkmenistan',
  'Uganda','Ukraine','United Arab Emirates','United Kingdom',
  'United States','Uruguay','Uzbekistan',
  'Vanuatu','Vatican City','Venezuela','Vietnam',
  'Yemen',
  'Zambia','Zimbabwe',
]

// Dial codes for PhoneInput.jsx — one row per entry in COUNTRIES above
// (name kept identical so the two lists can be cross-referenced), plus an
// ISO 3166-1 alpha-2 code the flag emoji is derived from at render time.
// `format` is an optional "what it looks like locally" example shown as
// the field's placeholder once that country is picked — only filled in for
// the handful of countries Eendrag alumni are actually likely to be in;
// everywhere else falls back to a generic placeholder.
// Shape: [name, iso2, dialCode, format?]
export const COUNTRY_DIAL_CODES = [
  ['Afghanistan', 'AF', '93'],
  ['Albania', 'AL', '355'],
  ['Algeria', 'DZ', '213'],
  ['Andorra', 'AD', '376'],
  ['Angola', 'AO', '244'],
  ['Antigua and Barbuda', 'AG', '1268'],
  ['Argentina', 'AR', '54'],
  ['Armenia', 'AM', '374'],
  ['Australia', 'AU', '61', '412 345 678'],
  ['Austria', 'AT', '43'],
  ['Azerbaijan', 'AZ', '994'],
  ['Bahamas', 'BS', '1242'],
  ['Bahrain', 'BH', '973'],
  ['Bangladesh', 'BD', '880'],
  ['Barbados', 'BB', '1246'],
  ['Belarus', 'BY', '375'],
  ['Belgium', 'BE', '32', '470 12 34 56'],
  ['Belize', 'BZ', '501'],
  ['Benin', 'BJ', '229'],
  ['Bhutan', 'BT', '975'],
  ['Bolivia', 'BO', '591'],
  ['Bosnia and Herzegovina', 'BA', '387'],
  ['Botswana', 'BW', '267'],
  ['Brazil', 'BR', '55'],
  ['Brunei', 'BN', '673'],
  ['Bulgaria', 'BG', '359'],
  ['Burkina Faso', 'BF', '226'],
  ['Burundi', 'BI', '257'],
  ['Cambodia', 'KH', '855'],
  ['Cameroon', 'CM', '237'],
  ['Canada', 'CA', '1', '(416) 555-0134'],
  ['Cape Verde', 'CV', '238'],
  ['Central African Republic', 'CF', '236'],
  ['Chad', 'TD', '235'],
  ['Chile', 'CL', '56'],
  ['China', 'CN', '86'],
  ['Colombia', 'CO', '57'],
  ['Comoros', 'KM', '269'],
  ['Congo', 'CG', '242'],
  ['Costa Rica', 'CR', '506'],
  ['Croatia', 'HR', '385'],
  ['Cuba', 'CU', '53'],
  ['Cyprus', 'CY', '357'],
  ['Czech Republic', 'CZ', '420'],
  ['Democratic Republic of the Congo', 'CD', '243'],
  ['Denmark', 'DK', '45'],
  ['Djibouti', 'DJ', '253'],
  ['Dominica', 'DM', '1767'],
  ['Dominican Republic', 'DO', '1809'],
  ['East Timor', 'TL', '670'],
  ['Ecuador', 'EC', '593'],
  ['Egypt', 'EG', '20'],
  ['El Salvador', 'SV', '503'],
  ['Equatorial Guinea', 'GQ', '240'],
  ['Eritrea', 'ER', '291'],
  ['Estonia', 'EE', '372'],
  ['Eswatini', 'SZ', '268'],
  ['Ethiopia', 'ET', '251'],
  ['Fiji', 'FJ', '679'],
  ['Finland', 'FI', '358'],
  ['France', 'FR', '33', '6 12 34 56 78'],
  ['Gabon', 'GA', '241'],
  ['Gambia', 'GM', '220'],
  ['Georgia', 'GE', '995'],
  ['Germany', 'DE', '49', '151 2345 6789'],
  ['Ghana', 'GH', '233'],
  ['Greece', 'GR', '30'],
  ['Grenada', 'GD', '1473'],
  ['Guatemala', 'GT', '502'],
  ['Guinea', 'GN', '224'],
  ['Guinea-Bissau', 'GW', '245'],
  ['Guyana', 'GY', '592'],
  ['Haiti', 'HT', '509'],
  ['Honduras', 'HN', '504'],
  ['Hungary', 'HU', '36'],
  ['Iceland', 'IS', '354'],
  ['India', 'IN', '91', '81234 56789'],
  ['Indonesia', 'ID', '62'],
  ['Iran', 'IR', '98'],
  ['Iraq', 'IQ', '964'],
  ['Ireland', 'IE', '353', '85 123 4567'],
  ['Israel', 'IL', '972'],
  ['Italy', 'IT', '39'],
  ['Ivory Coast', 'CI', '225'],
  ['Jamaica', 'JM', '1876'],
  ['Japan', 'JP', '81'],
  ['Jordan', 'JO', '962'],
  ['Kazakhstan', 'KZ', '7'],
  ['Kenya', 'KE', '254', '712 345 678'],
  ['Kiribati', 'KI', '686'],
  ['Kuwait', 'KW', '965'],
  ['Kyrgyzstan', 'KG', '996'],
  ['Laos', 'LA', '856'],
  ['Latvia', 'LV', '371'],
  ['Lebanon', 'LB', '961'],
  ['Lesotho', 'LS', '266'],
  ['Liberia', 'LR', '231'],
  ['Libya', 'LY', '218'],
  ['Liechtenstein', 'LI', '423'],
  ['Lithuania', 'LT', '370'],
  ['Luxembourg', 'LU', '352'],
  ['Madagascar', 'MG', '261'],
  ['Malawi', 'MW', '265'],
  ['Malaysia', 'MY', '60'],
  ['Maldives', 'MV', '960'],
  ['Mali', 'ML', '223'],
  ['Malta', 'MT', '356'],
  ['Mauritania', 'MR', '222'],
  ['Mauritius', 'MU', '230'],
  ['Mexico', 'MX', '52'],
  ['Moldova', 'MD', '373'],
  ['Monaco', 'MC', '377'],
  ['Mongolia', 'MN', '976'],
  ['Montenegro', 'ME', '382'],
  ['Morocco', 'MA', '212'],
  ['Mozambique', 'MZ', '258'],
  ['Myanmar', 'MM', '95'],
  ['Namibia', 'NA', '264', '81 123 4567'],
  ['Nepal', 'NP', '977'],
  ['Netherlands', 'NL', '31', '6 12345678'],
  ['New Zealand', 'NZ', '64', '21 123 4567'],
  ['Nicaragua', 'NI', '505'],
  ['Niger', 'NE', '227'],
  ['Nigeria', 'NG', '234', '802 123 4567'],
  ['North Korea', 'KP', '850'],
  ['North Macedonia', 'MK', '389'],
  ['Norway', 'NO', '47'],
  ['Oman', 'OM', '968'],
  ['Pakistan', 'PK', '92'],
  ['Panama', 'PA', '507'],
  ['Papua New Guinea', 'PG', '675'],
  ['Paraguay', 'PY', '595'],
  ['Peru', 'PE', '51'],
  ['Philippines', 'PH', '63'],
  ['Poland', 'PL', '48'],
  ['Portugal', 'PT', '351'],
  ['Qatar', 'QA', '974'],
  ['Romania', 'RO', '40'],
  ['Russia', 'RU', '7'],
  ['Rwanda', 'RW', '250'],
  ['Saint Kitts and Nevis', 'KN', '1869'],
  ['Saint Lucia', 'LC', '1758'],
  ['Saint Vincent and the Grenadines', 'VC', '1784'],
  ['Samoa', 'WS', '685'],
  ['Saudi Arabia', 'SA', '966'],
  ['Senegal', 'SN', '221'],
  ['Serbia', 'RS', '381'],
  ['Seychelles', 'SC', '248'],
  ['Sierra Leone', 'SL', '232'],
  ['Singapore', 'SG', '65'],
  ['Slovakia', 'SK', '421'],
  ['Slovenia', 'SI', '386'],
  ['Solomon Islands', 'SB', '677'],
  ['Somalia', 'SO', '252'],
  ['South Africa', 'ZA', '27', '82 123 4567'],
  ['South Korea', 'KR', '82'],
  ['South Sudan', 'SS', '211'],
  ['Spain', 'ES', '34'],
  ['Sri Lanka', 'LK', '94'],
  ['Sudan', 'SD', '249'],
  ['Suriname', 'SR', '597'],
  ['Sweden', 'SE', '46'],
  ['Switzerland', 'CH', '41'],
  ['Syria', 'SY', '963'],
  ['Taiwan', 'TW', '886'],
  ['Tajikistan', 'TJ', '992'],
  ['Tanzania', 'TZ', '255'],
  ['Thailand', 'TH', '66'],
  ['Togo', 'TG', '228'],
  ['Tonga', 'TO', '676'],
  ['Trinidad and Tobago', 'TT', '1868'],
  ['Tunisia', 'TN', '216'],
  ['Turkey', 'TR', '90'],
  ['Turkmenistan', 'TM', '993'],
  ['Uganda', 'UG', '256'],
  ['Ukraine', 'UA', '380'],
  ['United Arab Emirates', 'AE', '971', '50 123 4567'],
  ['United Kingdom', 'GB', '44', '7911 123456'],
  ['United States', 'US', '1', '(415) 555-2671'],
  ['Uruguay', 'UY', '598'],
  ['Uzbekistan', 'UZ', '998'],
  ['Vanuatu', 'VU', '678'],
  ['Vatican City', 'VA', '379'],
  ['Venezuela', 'VE', '58'],
  ['Vietnam', 'VN', '84'],
  ['Yemen', 'YE', '967'],
  ['Zambia', 'ZM', '260'],
  ['Zimbabwe', 'ZW', '263', '77 123 4567'],
]

// Shown pinned above the alphabetical list in PhoneInput's country dropdown
// — South Africa first since that's home turf for most Eendrag alumni, then
// a few of the other countries alumni most commonly end up in.
export const PHONE_PRIORITY_COUNTRIES = [
  'South Africa', 'United Kingdom', 'United States', 'Netherlands',
  'Australia', 'United Arab Emirates', 'Canada', 'New Zealand',
]

// Business profile options
// Generic fallback list — shown before an industry is picked, or when the
// chosen industry has no dedicated list below.
export const EXPERTISE_OPTIONS = [
  'Strategy & Business Development',
  'Finance & Investment',
  'Technology & Software',
  'Marketing & Sales',
  'Operations & Supply Chain',
  'Human Resources',
  'Legal & Compliance',
  'Engineering & Manufacturing',
  'Hospitality & Tourism',
  'Real Estate & Construction',
  'Agriculture & Food',
  'Education & Training',
  'Healthcare & Wellness',
  'Creative & Design',
  'Import/Export & Trade',
  'Non-Profit Management',
]

// Area-of-expertise options, tailored per industry (keys match INDUSTRIES
// exactly). Profile.jsx looks up the list for whatever industry is selected
// and falls back to EXPERTISE_OPTIONS if there isn't a dedicated one yet.
export const EXPERTISE_BY_INDUSTRY = {
  'Accounting & Finance': [
    'Financial Accounting & Reporting', 'Management Accounting', 'Corporate Tax', 'Personal Tax',
    'Auditing & Assurance', 'Bookkeeping', 'Payroll', 'Financial Planning & Analysis (FP&A)',
    'Treasury & Cash Management', 'Forensic Accounting', 'Budgeting', 'IFRS/GAAP Compliance',
    'Cost Accounting',
  ],
  'Agriculture & Wine': [
    'Viticulture', 'Winemaking & Oenology', 'Crop Production', 'Livestock Farming',
    'Agribusiness Management', 'Farm Operations', 'Agricultural Economics', 'Soil Science & Agronomy',
    'Irrigation & Water Management', 'Food Safety & Quality Control', 'Export & Trade (Agri Products)',
    'Sustainable/Organic Farming',
  ],
  'Architecture & Design': [
    'Residential Architecture', 'Commercial/Corporate Architecture', 'Urban Planning',
    'Interior Design', 'Landscape Architecture', 'Heritage & Restoration',
    'Sustainable/Green Building Design', '3D Visualisation & BIM', 'Construction Documentation',
    'Design Project Management', 'Product Design',
  ],
  'Civil Engineering': [
    'Structural Engineering', 'Geotechnical Engineering', 'Transportation/Roads Engineering',
    'Water & Sanitation Engineering', 'Bridges & Infrastructure', 'Project Management',
    'Construction Supervision', 'Surveying', 'Environmental Engineering', 'Municipal Engineering',
    'Site & Civil Design',
  ],
  'Software Engineering & Development': [
    'Frontend Development', 'Backend Development', 'Full-Stack Development', 'Mobile App Development',
    'DevOps & Infrastructure', 'Cloud Computing (AWS/Azure/GCP)', 'Data Engineering',
    'Machine Learning/AI', 'Cybersecurity', 'QA & Testing', 'Product Management (Tech)',
    'Engineering Leadership/CTO', 'UX/UI Engineering', 'Blockchain/Web3',
  ],
  'Mechanical/Manufacturing Engineering': [
    'Product Design & CAD', 'Process Engineering', 'Quality Assurance/Control',
    'Industrial Automation', 'Maintenance Engineering', 'Manufacturing Operations', 'HVAC Systems',
    'Tooling & Machining', 'Lean Manufacturing/Six Sigma', 'Robotics', 'Plant Management',
  ],
  'Other Engineering (electrical, chemical, marine, etc.)': [
    'Electrical Engineering', 'Chemical Engineering', 'Marine Engineering', 'Aerospace Engineering',
    'Mining Engineering', 'Industrial Engineering', 'Control & Instrumentation',
    'Renewable Energy Systems', 'Telecommunications Engineering', 'Process Design', 'Power Systems',
  ],
  'Banking & Financial Services': [
    'Retail Banking', 'Corporate/Commercial Banking', 'Private Banking & Wealth Management',
    'Credit & Risk Management', 'Treasury', 'Compliance & AML', 'Payments & Digital Banking',
    'Relationship Management', 'Trade Finance', 'Branch/Operations Management',
  ],
  'Insurance & Actuarial Science': [
    'Life Insurance', 'Short-Term/Personal Insurance', 'Underwriting', 'Claims Management',
    'Actuarial Modelling', 'Risk Assessment', 'Reinsurance', 'Insurance Broking',
    'Employee Benefits', 'Product Development (Insurance)',
  ],
  'Investment & Asset Management': [
    'Portfolio Management', 'Equity Research', 'Private Equity', 'Venture Capital', 'Hedge Funds',
    'Wealth Management', 'Financial Modelling & Valuation', 'Fund Administration',
    'Alternative Investments', 'Fixed Income',
  ],
  'Construction & Project Management': [
    'Site Management', 'Quantity Surveying', 'Project Scheduling & Planning',
    'Health & Safety (Construction)', 'Contracts Management', 'Cost Estimation',
    'Building Contracting', 'Civils/Infrastructure Delivery', 'Facilities Management',
    'Renovations & Fit-Outs',
  ],
  'Property & Real Estate': [
    'Residential Sales', 'Commercial Property', 'Property Development', 'Property Management',
    'Real Estate Investment', 'Property Valuation', 'Leasing/Letting',
    'Property Law & Conveyancing', 'Facilities Management', 'Real Estate Finance',
  ],
  'Legal': [
    'Corporate & Commercial Law', 'Litigation & Dispute Resolution', 'Property/Conveyancing Law',
    'Family Law', 'Criminal Law', 'Labour/Employment Law', 'Tax Law', 'Intellectual Property Law',
    'Mergers & Acquisitions', 'Compliance & Regulatory', 'Contract Drafting & Negotiation',
    'Banking & Finance Law',
  ],
  'Consulting': [
    'Strategy Consulting', 'Management Consulting', 'Financial/Risk Consulting',
    'IT/Technology Consulting', 'HR Consulting', 'Operations Consulting', 'Change Management',
    'Business Process Improvement', 'M&A Advisory', 'Sustainability/ESG Consulting',
  ],
  'Management & Operations': [
    'General Management', 'Operations Management', 'Business Strategy', 'Supply Chain Management',
    'Process Improvement', 'Team Leadership', 'Project/Programme Management', 'Change Management',
    'Performance Management', 'Business Development',
  ],
  'Human Resources & Recruitment': [
    'Talent Acquisition/Recruitment', 'HR Business Partnering', 'Learning & Development',
    'Compensation & Benefits', 'Employee Relations', 'Organisational Development',
    'HR Policy & Compliance', 'Performance Management', 'Employer Branding', 'Executive Search',
  ],
  'Marketing & Advertising': [
    'Brand Management', 'Digital Marketing', 'Social Media Marketing', 'Content Marketing',
    'Advertising Campaigns', 'Market Research', 'Product Marketing', 'Growth Marketing',
    'Email/CRM Marketing', 'SEO/SEM', 'Creative Direction',
  ],
  'Media & Creative (publishing, film, design)': [
    'Graphic Design', 'Film & Video Production', 'Photography', 'Journalism/Editorial', 'Publishing',
    'Copywriting', 'Animation & Motion Graphics', 'Broadcasting', 'Music Production', 'Illustration',
    'Content Creation',
  ],
  'Public Relations & Communications': [
    'Media Relations', 'Corporate Communications', 'Crisis Communications',
    'Internal Communications', 'Reputation Management', 'Event Management',
    'Stakeholder Engagement', 'Speechwriting', 'Public Affairs', 'Social Media Communications',
  ],
  'Education & Academia': [
    'Primary/Secondary Teaching', 'Higher Education/Lecturing', 'Curriculum Development',
    'Educational Leadership/Admin', 'Academic Research', 'Tutoring', 'Special Needs Education',
    'EdTech', 'Training & Facilitation', 'School Governance',
  ],
  'Research & Development': [
    'Scientific Research', 'Product R&D', 'Innovation Management', 'Applied Research',
    'Data Analysis & Statistics', 'Laboratory Management', 'Grant Writing/Funding',
    'Prototyping & Testing', 'Technology Transfer',
  ],
  'Healthcare & Medical': [
    'General Practice/Medicine', 'Surgery', 'Nursing', 'Specialist Medicine', 'Dentistry',
    'Physiotherapy', 'Radiology', 'Emergency Medicine', 'Healthcare Administration', 'Public Health',
    'Medical Research', 'Occupational Therapy',
  ],
  'Pharmaceuticals & Biotech': [
    'Drug Development', 'Clinical Research/Trials', 'Regulatory Affairs', 'Pharmacovigilance',
    'Pharmaceutical Sales', 'Biotechnology Research', 'Quality Assurance (Pharma)',
    'Manufacturing (Pharma)', 'Pharmacy',
  ],
  'Mental Health & Psychology': [
    'Clinical Psychology', 'Counselling', 'Psychiatry', 'Occupational/Organisational Psychology',
    'Educational Psychology', 'Family/Marriage Therapy', 'Substance Abuse Counselling',
    'Trauma Therapy', 'Life/Executive Coaching', 'Child & Adolescent Psychology',
  ],
  'Energy & Environment': [
    'Renewable Energy (Solar/Wind)', 'Oil & Gas', 'Energy Efficiency', 'Environmental Management',
    'Sustainability & ESG', 'Climate Change/Carbon', 'Water Resource Management', 'Waste Management',
    'Environmental Compliance', 'Power Generation',
  ],
  'Mining & Resources': [
    'Mine Management', 'Geology', 'Mining Engineering', 'Metallurgy', 'Mineral Processing',
    'Mine Safety', 'Mining Finance', 'Exploration', 'Resource Economics',
    'Environmental Rehabilitation',
  ],
  'Manufacturing & Industrial': [
    'Production Management', 'Quality Control', 'Supply Chain/Procurement', 'Industrial Engineering',
    'Health & Safety', 'Plant Operations', 'Automation', 'Lean Manufacturing/Six Sigma',
    'Product Development', 'Maintenance & Reliability',
  ],
  'Hospitality & Tourism': [
    'Hotel Management', 'Guest Services/Front Office', 'Food & Beverage Management',
    'Event Management', 'Tour Operations/Travel', 'Tourism Marketing', 'Restaurant Management',
    'Guiding', 'Hospitality Training', 'Resort/Lodge Management',
  ],
  'Food & Beverage': [
    'Food Production', 'Culinary Arts/Chef', 'Beverage Production', 'Food Safety & Quality',
    'Product Development (Food)', 'Supply Chain (F&B)', 'Restaurant/Catering Management',
    'Nutrition', 'Retail F&B', 'Brewing/Distilling',
  ],
  'Retail & Wholesale': [
    'Store Management', 'Merchandising', 'Buying & Procurement', 'Retail Operations',
    'Category Management', 'Visual Merchandising', 'Wholesale Distribution', 'Customer Experience',
    'Inventory Management', 'Franchise Management',
  ],
  'E-commerce': [
    'Online Store Management', 'Digital Marketing (E-commerce)',
    'Marketplace Management (Amazon/Takealot etc.)', 'Fulfilment & Logistics',
    'Conversion Rate Optimisation', 'UX for E-commerce', 'Payment Systems', 'Dropshipping',
    'Product Listing/Cataloguing', 'Customer Service (E-commerce)',
  ],
  'Transport & Logistics': [
    'Supply Chain Management', 'Freight Forwarding', 'Fleet Management', 'Warehouse Management',
    'Distribution & Delivery', 'Shipping/Maritime', 'Import/Export', 'Logistics Planning',
    'Procurement & Sourcing', 'Route Optimisation',
  ],
  'Telecommunications': [
    'Network Engineering', 'Telecoms Infrastructure', 'Mobile/Wireless Technology', 'Fibre/Broadband',
    'Telecoms Sales', 'RF Engineering', 'Systems Integration', 'Telecoms Regulation',
    'Customer Support (Telecoms)',
  ],
  'Utilities & Water': [
    'Water Treatment & Supply', 'Electricity Distribution', 'Utility Operations',
    'Infrastructure Maintenance', 'Metering & Billing', 'Regulatory Compliance (Utilities)',
    'Wastewater Management', 'Grid Management', 'Renewable Integration',
  ],
  'Government & Public Sector': [
    'Public Policy', 'Public Administration', 'Municipal Government', 'Diplomacy/Foreign Service',
    'Law Enforcement', 'Public Finance', 'Urban/Regional Planning', 'Regulatory Affairs',
    'Political Advisory', 'Social Services',
  ],
  'Non-profit & NGO': [
    'Programme Management', 'Fundraising & Donor Relations', 'Community Development',
    'Advocacy & Policy', 'Volunteer Management', 'Grant Writing', 'Humanitarian Aid',
    'Monitoring & Evaluation', 'NGO Leadership/Governance', 'Social Impact Strategy',
  ],
  'Sport & Recreation': [
    'Coaching', 'Sports Management', 'Sports Science', 'Sports Marketing/Sponsorship',
    'Personal Training/Fitness', 'Sports Administration', 'Event/Tournament Management',
    'Talent Development', 'Sports Broadcasting', 'Sports Physiotherapy',
  ],
  'Arts & Entertainment': [
    'Performing Arts (Theatre/Dance)', 'Music', 'Film & TV Production', 'Visual Arts',
    'Event/Concert Production', 'Talent Management', 'Curation/Gallery Management',
    'Entertainment Law', 'Creative Writing', 'Arts Administration',
  ],
  'Military & Defence': [
    'Combat/Operations', 'Military Logistics', 'Defence Intelligence', 'Cybersecurity/Defence Tech',
    'Military Engineering', 'Naval/Maritime Operations', 'Aviation/Air Force Operations',
    'Defence Procurement', 'Strategic Planning', 'Veteran Affairs',
  ],
  'Retired': [
    'Mentoring & Coaching', 'Board & Advisory Roles', 'Community Volunteering',
    'Consulting (Semi-Retired)', 'Industry Knowledge & Networks',
  ],
  'Student': [
    'Internships & Vacation Work', 'Academic Research', 'Student Leadership',
    'Part-Time/Freelance Work', 'Career Exploration',
  ],
}

// Consolidated: Services & Opportunities (merged Services + Collaboration)
export const SERVICES_OFFERED = [
  'Mentoring/Coaching',
  'Consulting',
  'Technical Expertise',
  'Job Opportunities',
  'Investment/Funding',
  'B2B Partnerships',
  'Client Referrals',
  'Supplier Introductions',
  'Market Insights',
  'Network Connections',
]

// Kept for backward compatibility but no longer shown in UI
export const COLLABORATION_TYPES = [
  'B2B Partnerships',
  'Joint Ventures',
  'Mentorship',
  'Investor Connections',
  'Supplier Relationships',
  'Client Referrals',
  'Knowledge Sharing',
  'Recruitment',
]

// Improved: Clearer, more discoverable business categories
export const BUSINESS_CATEGORIES = [
  'Founder/Entrepreneur',
  'Corporate Executive',
  'Investor/Advisor',
  'Service Provider',
  'Product Company',
  'Consultant/Freelancer',
  'Job Creator/Recruiter',
  'Non-Profit Leader',
]

// New: Availability/Capacity
export const AVAILABILITY_OPTIONS = [
  'Available now',
  'Part-time available',
  'By request/ad-hoc',
  'Fully booked',
]

// New: Geographic focus
export const GEOGRAPHIC_FOCUS = [
  'Local (South Africa)',
  'Pan-Africa',
  'Global',
  'Remote only',
]
